# .streamlit/secrets.toml

[connection.supabase]
url = "https://kwztayzyjudbycuvvnlw.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3enRheXp5anVkYnljdXZ2bmx3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDgyNDg0MzAsImV4cCI6MjAyMzgyNDQzMH0.5vGAUJ0kwj4jxM1pG8yMbmGeyQKJeRWzNxWl8y1K1As"